### ISSUE TITLE
Outer ports disappear when attempting to make connection from inner ports

### ISSUE THREAD

**Issue by J75880** [ZeligsoftDev/CX4CBDDS#117]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
So, if I have component A that has a single component  and within it a component named component B and both components have an identical single port, then I’d want to connect the port interface from component B to A (inner to outermost). However, right now when I attempt to do so, component A’s port interface appears to disappear (hidden by a filter maybe?) and the connection is hidden.

**Comment by ysroh** [comment]
Reported this issue against Papyrus so we can track.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=562586

**Comment by ysroh** [comment]
Papyrus Canonical edit policy removes inherited ports from the view since inherited ports not considered as part of semantic children. I am not sure why. 
In order to fix this issue without Papyrus commit, we need to install our own edit policy to put inherited ports back to the diagram view. I will try this to see if it works well or not.

**Comment by ysroh** [comment]
Fixed. You need to add external ports to the existing diagram using "Filters->Show/Hide contents" first. Ports will be visible automatically if it is a new diagram.

**Comment by j26151** [comment]
I have verified this. You can close this issue.
