### ISSUE TITLE
Log entry introduced for org.eclipse.papyrus.infra.ui.editor.IMultiDiagramEditor

### ISSUE THREAD

**Issue by ysroh** [ZeligsoftDev/CX4CBDDS#150]
# **Issue and tracking information**

The following log entry appears in the console due to the new IMultiDiagramEditor registration.
We should investigate if there could be any unexpected consequences of this issue.

!ENTRY org.eclipse.papyrus.infra.core 2 0 2020-06-18 12:26:51.949
!MESSAGE Two services with same priority (1) are declared under key 'org.eclipse.papyrus.infra.ui.editor.IMultiDiagramEditor'. Keep the first encountered only.

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by eposse** [comment]
This is caused by my commit 9954a6b1345b466874affcfa02ea500707b05b0e from pull request #146. 

The warning message can be ignored and there do not seem to be any negative side effects. 

Normally, when opening a model, Papyrus registers a `IMultiDiagramEditor` service, in particular an instance of `org.eclipse.papyrus.editor.PapyrusMultiDiagramEditor`. Now, to resolve issue #136, I introduced a "dummy" service called `CoreMultiDiagramEditorService`. Both classes inherit from `CoreMultiDiagramEditor`. Now, after merging commit 9954a6, this new `CoreMultiDiagramEditorService` is registered first. Then when Papyrus tries to register the original `PapyrusMultiDiagramEditor` you get the warning. However the message incorrectly states that only the first one is kept. After debugging this, it is clear that in fact, only the original `PapyrusMultiDiagramEditor` service is kept in the registry, and therefore any clients of the service will get this one.

Note that this is a different use case than when using Papyrus Compare, as the later won't register the `PapyrusMultiDiagramEditor` service  and therefore it needs the new `CoreMultiDiagramEditorService`.

It will be possible to get rid of the warning by updating the priority given to the new `CoreMultiDiagramEditorService` so that it gets a lower priority.

**Comment by eposse** [comment]
Fixed and reviewed by Paul.
