### ISSUE TITLE
Palette missing graphical drawing objects

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#208]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**
Palette is missing all the graphical drawing objects making it impossible to represent any hardware or non-SNA "things" on, say, a context diagram (e.g. cannot draw any of these objects including important things like indications it will be used in an air gapped network somewhere). These graphical items include sticky notes, squares, lines, etc.. We understand that while RSA supported geometric objects and that Papyrus does not, this is something our users require when trying to show how the model interacts with other aspects of the system via the model.

**Comment by ysroh** [comment]
@J17359  I assume that you are referring to assembly diagram?

**Comment by J17359** [comment]
@ysroh sorry, yes, that is correct. We (SNA) sometimes put an assembly diagram above the "main" assembly diagram for a project to show the context of that assembly within the system. We call that top-level diagram the "context diagram" which is just an assembly diagram under the covers.

So to clarify, we want the ability to draw objects on assembly diagrams (things like circles, squares, lines, etc.) in order to show visually the context of where the main assembly diagram fits within a system or mark it unclassified/classified.

**Comment by ysroh** [comment]
@J17359 Thanks for the clarification.  I will start working on this issue.

**Comment by ysroh** [comment]
Papyrus issue raised: https://bugs.eclipse.org/bugs/show_bug.cgi?id=570148

**Comment by ysroh** [comment]
The geo shapes palette drawer is added to the Structure diagram. However, the sketch shapes are not available since they are coming from one of the IBM packages

These geo shapes are not supported by Papyrus but I was able to override default Papyrus behaviour so we can create them in the diagram.
The comment palette item is also added to the Assembly palette drawer so you can create Comment as well.

There are two issues that cannot be fixed without touching the Papyrus core.
The first issue is that a newly created shape is not filled with the correct color.
The workaround for this issue is
1. Select the shape and open Appearance properties tab
2. De-activate gradient feature like below
![image](https://user-images.githubusercontent.com/896503/104223236-61fbc800-5411-11eb-8926-b6979bd08bbc.png)
3. Now if you select a new fill color then the shape will be filled with that color.

The second issue is that the Delete menu is not available for the line connector. See the snapshot below.
![image](https://user-images.githubusercontent.com/896503/104223782-15fd5300-5412-11eb-83a7-158bfb5a8231.png)

The workaround is:
Use Edit->Cut menu to delete.
![image](https://user-images.githubusercontent.com/896503/104224003-5ceb4880-5412-11eb-9ca7-279fc5adfbcd.png)

Please let us know if you have any comments or find any other issues.

**Comment by j26151** [comment]
Do we have bugs or issues written to address the two issues mentioned above? Everything looks good, but being able to delete that line would be important. Setting a default color for the shapes would be useful too.

**Comment by ysroh** [comment]
Added "Delete Selected Line" menu to delete the line.
![image](https://user-images.githubusercontent.com/896503/104466899-b58e2300-5583-11eb-9ce3-a854b20197fd.png)

**Comment by ysroh** [comment]
I am also trying to disable the Gradient feature when a new geo shape is created to see if the shape will be filled with the correct color.

**Comment by ysroh** [comment]
The default fill color issue is now fixed. 
Please close this issue if all verified.

**Comment by j26151** [comment]
Both of these issues are fixed. Thank you. The last thing I would ask is if for deleting the line, how difficult would it be to delete the line by clicking the delete key as well? This isn't critical, but I can see our users complaining about it.

**Comment by ysroh** [comment]
Added delete short key binding. Let me know if you have any other comments. thanks.

**Comment by j26151** [comment]
I works great! Thank you for such a fast turnaround. I would say this ticket can be closed now.
