### ISSUE TITLE
Generate descriptors does not generate correct node name in CDD file

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#228]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**

When creating a Domain in CX, you must give nodes a name, like "node1". If in the deployment plan, you use that domain, but change the name of the node from "node1" to "node1Test", the generated CDP and CDD files do not match. The CDD keeps "node1" and the CDP file expects "node1Test".

**Comment by ysroh** [comment]
Fixed. Correct node name is generated in CDD file. Disabled name field in component & port deployment part in CX properties view. Users will be able to change any top level deployment part and node names.

**Comment by j26151** [comment]
@ysroh Can you explain your fix here? Did you restrict users from changing the node name in a deployment plan from "node1" to "node1Test" (option number 1 above), or did you do something else?

**Comment by ysroh** [comment]
@j26151 Sorry that I wasn’t clear about the fix. 
So users will be able to change the node name from “node1” to “node1Test” and the new name will be reflected in the deployment editor. The cdd file will also use the new name. 

However, the name fields of components and ports are disabled in the CX properties view. It is because the new names were never used in the generation and didn’t even show up in the deployment editor. So users were able to change the name from the deployment but didn’t do anything. 

I disabled the name field rather than changing our generator to use these new names from components parts and ports because it will be a lot more work to change how we traverse elements during the generation. 

If you need the functionality to change these component and port names in the deployment editor rather than changing from assembly diagram then let us know so we create a new ticket to implement the enhancement. 

Thanks

**Comment by j26151** [comment]
That sounds like a reasonable solution to me. Thank you. We will let you know when we get the chance to test it on our end.

**Comment by j26151** [comment]
I have verified that this works on our end. Thank you.

**Comment by ysroh** [comment]
Thanks.. I will close this issue.
