### ISSUE TITLE
Show/Hide Contents Dialog for Assembly Diagrams is Broken

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#257]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**
Once made visible, either by default or post-creation manual enable, it is not possible to hide Property and Attributes boxes on component assemblies on assembly diagrams.  They clutter up all diagrams with unnecessary information, get in the way of port names, and generally add information of little value to these diagrams.

Per the screenshot of a "Filters -> Show/Hide Contents" dialog invoked from a component assembly's context menu, if you uncheck the box for the example Property and Attribute on that assembly component and hit OK, they still remain visible.  Moreover, when you bring up the dialog again, the boxes are once again checked.
![image](https://user-images.githubusercontent.com/46937599/121515266-03844700-c9bb-11eb-96b8-396b27e5c232.png)

And closely related to this primary issue is the secondary frequent complaint that Properties created by default, such as the RegisterNaming property, are visible at all initially.  If possible, newly created Property and Attribute elements owned by a parent Component should default to NOT being visible on diagrams.

**Comment by ysroh** [comment]
@J17359 Do you ever need to put those properties or attributes back to the diagram? The reason why I am asking is that the diagram is currently synced with the model so it cannot run mixed mode. I can hide the attributes from the diagram but you won't be able to put them back again unless you turn off the "Sync with model" option from the Appearance tab. So let me know if you really need to have the option to see these attributes from the diagram without turning off sync option then I will come up with a solution.

**Comment by ysroh** [comment]
> @ysroh Our users have never had a need to view properties or attributes on a composite structure diagram, which is almost always used only to define the run-time design of the internals of an assembly component. Don't see a problem with making it hard (or impossible?) to make them visible again once turned off (or turned off initially).

Thanks. I will hide attributes.

> We've noticed that comment/documentation blocks on elements in the model may also show up on the composite structure diagrams, which is similarly undesirable.

Can you let me know how I can reproduce this? I only see comments block if I show the internal structure of the part. If that's the problem then I will hide them from the internal structure compartment.

> And also presumably related, this same issue of show/hide dialog visibility checkboxes being ignored happens on the Show/Hide Compartments dialog as well.

> Will/can whatever fix is appropriate take care of all of these issues related to what's visible on diagrams?

I don't think it would be an easy fix just because we might have to fix Papyrus itself if we cannot find a workaround to override base functionality. I was lucky to find a workaround for most of the problems we had so far but I am not really sure about this.
Do we know if you want to make some compartments visible all the time? I think that could be an easy fix to start with until we find a workaround so users can actually turn them off or on.
So can you please let me know which compartments you want to make visible? so I can focus on them?

**Comment by MHayman5** [comment]
After further investigation the comment/documentation blocks that show up are only in the case of adding comments to an assembly or monolithic implementation model element, vs. their parent CCMComponent element.  Comments are supposed to be applied to the CCMComponent parent, not to their child implementations.  So likely not a problem.

However, there are users that are adding a new Composite Structure Diagram to a parent CCMComponent element for whatever reason (apparently to add ports to it), at which point valid comments on the parent CCMComponent do show up in these diagrams.  But it's not clear that's a valid use case, since a composite structure diagram under a CCMComponent vs. an impl of it doesn't make a lot of sense.  In the RSA CX product composite structure diagrams were only (allowed to be) added under AssemblyImplementation elements.

As for Show/Hide Compartments, the default only has "internal structure" checked on the left column, plus the unlabeled and unexplained "Display Compartment Title" box at the bottom of the right column.  This is fine and apparently a good default.  The problem comes in when users try to turn on or change anything in the Show/Hide Compartments dialog.  Other labels and/or compartments appear on the diagram as expected, but then they cannot be gotten rid of if you go back and try to uncheck them.  This happens a lot since users are modifying all the Filter visibility settings they can find in a quest to get rid of the display of various superfluous elements like properties, attributes and comments.  But once any of these things become visible, you can never get rid of them on the diagram again.

**Comment by ysroh** [comment]
Please see comments inline
> After further investigation the comment/documentation blocks that show up are only in the case of adding comments to an assembly or monolithic implementation model element, vs. their parent CCMComponent element. Comments are supposed to be applied to the CCMComponent parent, not to their child implementations. So likely not a problem.

Understood.

> 
> However, there are users that are adding a new Composite Structure Diagram to a parent CCMComponent element for whatever reason (apparently to add ports to it), at which point valid comments on the parent CCMComponent do show up in these diagrams. But it's not clear that's a valid use case, since a composite structure diagram under a CCMComponent vs. an impl of it doesn't make a lot of sense. In the RSA CX product composite structure diagrams were only (allowed to be) added under AssemblyImplementation elements.

That's right. I don't think it makes sense to create a composite structure diagram under CCM component.
However,  I am not sure if I want to hide the comments from the diagram since it is a valid use-case to add comments on a composite diagram using the palette entry.

> 
> As for Show/Hide Compartments, the default only has "internal structure" checked on the left column, plus the unlabeled and unexplained "Display Compartment Title" box at the bottom of the right column. This is fine and apparently a good default. The problem comes in when users try to turn on or change anything in the Show/Hide Compartments dialog. Other labels and/or compartments appear on the diagram as expected, but then they cannot be gotten rid of if you go back and try to uncheck them. This happens a lot since users are modifying all the Filter visibility settings they can find in a quest to get rid of the display of various superfluous elements like properties, attributes and comments. But once any of these things become visible, you can never get rid of them on the diagram again.

I can reproduce this problem. I will work on it. Thanks.

**Comment by ysroh** [comment]
It is not possible to override the behaviour of the existing show/hide compartment filter so I would like to add a menu to reset the compartment filter to go back to the initial setting.

Let me know if you are ok with this solution.

![image](https://user-images.githubusercontent.com/896503/122079798-beea1880-cdcb-11eb-9e73-46df25bed025.png)

**Comment by MHayman5** [comment]
Sounds like a workable solution, as long as the initial defaults are OK.  For Compartments we believe they are.  For Contents probably not (e.g., properties, attributes and comments on components).

**Comment by ysroh** [comment]
I will have the fix soon but my assumption is that the structure diagram is created under the assembly. I will create a separate ticket to disable the creation of the structure diagram from the component.

**Comment by ysroh** [comment]
I will also hide attributes/properties/comments from the composite structure diagram created under the CCMComponent for now.

**Comment by ysroh** [comment]
Fixed. Please verify the fix and let me know if you have any comments. Thanks

**Comment by rgs424** [comment]
Hi, I am trying to verify this feature. Am I supposed to see this menu item? I just want to make sure I am looking for the right thing.


![image](https://user-images.githubusercontent.com/13985583/122575348-a6be0780-d01e-11eb-928f-0f204183eaf6.png)

**Comment by ysroh** [comment]
Yes. The menu is there to reset compartment settings. The reason is that if you enable some compartments using Show/Hide compartments menu there are some visible items that you can never get ride of. You need to verify that everything looks good in diagram after running the reset compartment menu. 
One way to test this is to enable all compartments via Show/Hide compartments menu and then run reset menu to see if the diagram looks good.

**Comment by J17359** [comment]
We've tested and verified the fix on new models. Still doing some more testing on existing models to see if the behavior matches what we'd expect. I'll respond back when that testing is complete.

**Comment by J17359** [comment]
This ticket can be closed @ysroh - additional testing continued to prove that it was working. Thanks!

**Comment by ysroh** [comment]
Thanks
