### ISSUE TITLE
Improve Model Explorer so users can view all models at once

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#271]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**
When you first open a project and switch to the Model Explorer tab, you're presented with the message "No Models Available"  Its very non-intuitive that you have to switch to the Project Explorer tab double click on a model file and then switch back to the Model Explorer tab in order to see the models. It felt more intuitive with RSA and its virtual Models/Diagrams folders in the Project Explorer tab.  So could we do one of the following:
* Get rid of Model Explorer tab and duplicate the virtual folders functionality that RSA had in Project Explorer tab

OR

* Show all models in Model Explorer tab as closed.  This way you can double click on one and it opens that model and all the referenced models, and you can do this for any of the models. And this would include the ability to open multiple models at one time.

**Comment by ysroh** [comment]
@J17359 Replacing the current Model Explorer with the virtual folder in Project explorer will require extensive work overriding how resource management work in Papyrus. The model explorer and the properties view are also tied together so I would say this option is not feasible.

The Model Explorer is tied to an open Papyrus editor in order to get contents so it is not possible to add unopened models in the Model explorer as you suggested. Believe me, I hate this Model explorer as much as you do but that's how Papyrus work, unfortunately.

I am trying to see if I can find a way to make things simpler by using filter capability in the project explorer or adding a menu to open referenced models easily within the current model. I will prototype some possibilities and let you know.

**Comment by ysroh** [comment]
Fix merged to Papyrus branch. Let me know if you have any comments.

**Comment by j26151** [comment]
Both of these fixes work great. Thank you. This issue can be closed.

**Comment by ysroh** [comment]
Thanks
