### ISSUE TITLE
Need to investigate a way to generate only certain information for specific port types with DDS

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#397]
# **Issue and tracking information**
Recently we encountered an issue where a component with a DDS_Write port whose dataspace is configured to have a push_consumer content filter would create DDS_Subscriber entities when we ran our code. After speaking to RemedyIT, they informed us that the issue is that the configuration properties for a "content filter" cause their middleware to create all entities that a content filter would require, thus, subscriber entities.  

The solution here would be that the configuration properties for a DDS_Write port would never include content filter config properties for either push or pull consumer filters.

However, I realize that this might not be straight forward. This would likely be a hack. Do you know of anyway that you can configure the DDS_DCPS model that you create and maintain for us such that its ports only use certain config properties and ignore others?

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by jwillemsen** [comment]
The DDS4CCM Event connector (https://github.com/RemedyIT/ciaox11/blob/09a25cf421d27ed2b6f47e66f95bd7bb45a89a9c/connectors/dds4ccm/idl/ccm_dds.idl#L316) combines 3 different extended ports, each for a different role. The AXCIOMA Event connector implementation contains the code for all 3 extended ports, but at runtime the necessary objects are only created when an extended port is used (meaning one of the ports are connected or the attributes set through the deployment plan). At the moment an extended port is not used the ports are not connected, but also the related attributes shouldn't be set through the deployment plan.

**Comment by j26151** [comment]
Additionally, while I can't think of a use-case at the moment, we might want a solution that is flexible for future connectors that could have a similar issue. I.e. multiple ports with different attributes for each.

**Comment by eposse** [comment]
Hi. I've been working on a solution to this and have a couple of questions.

First, the approach to solve this, suggested by @ysroh was to filter the push_consumer (and pull_consumer) properties from view in the Properties section of the DDS_Write port, that way, the user could not modify its properties and therefore the corresponding configuration would not be generated in the .cdp descriptor.

However we are not entirely certain that this will be enough, because the properties would still be visible in the connector's properties, and editable there, which results in generating those configuration values for the relevant process.

So we wanted to confirm with you, your workflow.

To be more precise, here's what I mean, using the BasicPubSub example.

First, here you see the testDataPub port, which is a DDS_Write port, selected, and as you can see below, its "push_consumer" and "pull_consumer" properties have been filtered out, and therefore cannot be edited *for this port*:


![filtered_properties](https://user-images.githubusercontent.com/3011155/172711100-85ed41ef-7665-49a7-b0c9-366a954654ff.png)


However these are *not* filtered from view when we select the TestData_conn connector itself:


![connector_defaults](https://user-images.githubusercontent.com/3011155/172711229-9533f78f-f858-4be6-985d-73e027b60a89.png)


If we generate the descriptors, neither the instance element for BasicPublisher_proc nor BasicSubscriber_proc will include a "push_consumer_filter" configProperty.

On the other hand, if we modify one of the default values, under the connector itself (rather than the testDataPub port), as shown below,


![connector_defaults_updated](https://user-images.githubusercontent.com/3011155/172711947-09182f32-1e05-4ad3-b0c7-b6d6d2aacdb9.png)


and then we generate the descriptors, then the generated descriptors *will* include the "push_consumer_filter" configProperty for both BasicPublisher_proc and BasicSubscriber_proc.

Our understanding of this issue is that when the .cdp descriptor contains such "push_consumer_filter" configProperty in the publisher, then you get the undesired DDS_Subscriber entities created by the middleware. Is this correct?

If this is correct, we are wondering if it is part of your user workflow to allow the modification of default values in the connector itself (like TestData_conn) or not. Or rather, what should happen if the user modifies the defaults in the connector itself?

Currently, as shown in the example above, if you modify the defaults in the connector itself, then those will be inherited by the port (testDataPub in this case) and these will result in generating the configProperty in the descriptor.

So, if a user modifies the defaults in the connector itself, should the generator generate the configProperty for the BasicPublisher_proc or should it not generate such configProperty in spite of the fact that the connector has set a default (for its "push_consumer"?

**Comment by MHayman5** [comment]
@eposse , first yes it's common in a deployment plan editor to set properties on a connector instance that are intended to automatically propagate to all extended port types on component ports that connect to it in an assembly definition.  This is the typical way of setting config parameters that component ports are intended to share in order to communicate.  Like the topic_name, domain_id and qos_profile in particular.  Else you'd have to set them all explicitly on each component port, and be very careful to ensure they're all set exactly the same, else they won't connect/communicate.

Setting default properties unique to each extended port type a connector provides is less common than setting it explicitly on a component port, but it's also done.

When you type a component port on a component type definition with a GIS extended port type defined by a GIS connector, of which there may be many, the type includes only one of the extended port types.  The DDS4CCM spec defines two GIS connectors, DDS_State and DDS_Event. Using the DDS_Event GIS connector as an example, it offers 3 extended port types.  A component port that uses the publisher interaction pattern from DDS_Event can only be typed with the DDS_Write (supplier) extended port type, but a subscriber port can choose from either DDS_Get (pull_consumer) or DDS_Listen (push_consumer).  The DDS4CCM DDS_State GIS connector also offers only one extended port option for publisher ports (DDS_Update (observable)), but four different extended port options for subscribers.

We know for sure that the CX model types GIS ports to include both the GIS connector type/instance  as well as one of its available extended port types.  Else it would not be able to auto-generate the component IDL files that define the model-typed extended port option.  For instance, an extended port definition in IDL syntax for a subscriber could be either "port MyConnector_conn::DDS_Listen myPortSub;" or "port MyConnector_conn::DDS_Get myPortSub;" for a subscriber, depending upon how it's typed.  The model knows whether it uses the DDS_Listen or DDS_Get extended port type on the connector.

Given that the model includes the extended port type as part of a component port type definition, ideally any "default" settings from the parent connector type/instance it is typed from that are set on extended ports that is NOT typed to use, would not propagate to the descriptor file config properties generated for that component instance.  Only the defaults set under the extended port type it is typed to use.

**Comment by eposse** [comment]
Thank you @MHayman5. So, to be absolutely clear, and make it more concrete, in the example that I showed above, the parent connector type/instance is DDS_Event, and if the user edits its "default" settings under TestData_conn, in particular, it edits the query filter under "push_consumer", then, in the generated descriptor file, the "push_consumer_filter" configProperty should appear *only* under the component implementation of the subscriber (BasicSubscriber_proc) but not under the implementation of the publisher (BasicPublisher_proc) because in this one, the port testDataPub is a DDS_Write port, whereas the subscriber port testDataSub is a DDS_Listen port.

Is this correct?

I'm attaching two files to make it explicit what I mean. The file "BasicPubSub_defaults_updated_original.cdp.txt" contains the descriptor as it is currently generated by CX, where the configProperty appears in both the subscriber and publisher instances, and the "BasicPubSub_defaults_updated.cdp.txt" is what we understand should be the correct descriptor, including the configProperty only in the subscriber instance.

Is this correct?

Thanks


[BasicPubSub_defaults_updated.cdp.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/8872674/BasicPubSub_defaults_updated.cdp.txt)
[BasicPubSub_defaults_updated_original.cdp.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/8872675/BasicPubSub_defaults_updated_original.cdp.txt)

**Comment by j26151** [comment]
Yes, that is exactly the behavior that we are looking for. The thing we want to ensure though is that this isn't a special if statement specific to CCM_DDS but that this behavior is seen with all connectors/ports. E.g. if there was a similar situation with the PSDD connector and ports, we would want this solution to just "work" there as well.

**Comment by eposse** [comment]
Thanks for the clarifications. The solution we are proposing to support other connector/port types is to use an extension point to register properties that you would like filtered out for that type. Currently we only have the case for DDS_Write + push_consumer/pull_consumer, but if new cases arise, it should be a matter of registering a new connector/port type property with the extension point.

**Comment by j26151** [comment]
My only questions for this would be how would someone specify these extension points? Sometimes we create model libraries that contain connectors that we install as model libraries (install into eclipse) and other times we just have the connector's model referenceable in the workspace (imagine CCM_DDS's model in the workspace and we use dynamic pathmapping to reference it)?

**Comment by eposse** [comment]
Our current approach is to define the filtered properties in the "com.zeligsoft.domain.idl3plus.model_library_configuration" extension point which was already used in the com.zeligsoft.domain.dds4ccm.ddsdcspconnector and com.zeligsoft.domain.dds4ccm.psddconnector plugins. This extension point was defined to configure aspects of the model libraries, such as port icons. We extended it to allow the specification of properties to filter. Since we are filtering properties for a DDS_DCSP connector, we are (currently) specifying the properties to filter only on the former. 

Here's what it looks like in Eclipse:
![filtered_properties_extension_point](https://user-images.githubusercontent.com/3011155/173379369-34a3960c-5ed6-4925-bcc1-cd2e2e60090a.png)

As you see, we add an element (highlighted) whose name is the connector type fully qualified name (in this case DDS_DCPS::CCM_DDS::Typed::DDS_Write) and whose children are the names of properties (ports) to filter (or regular expressions if you want to filter many at once).

So if you have custom libraries, you would add the "com.zeligsoft.domain.idl3plus.model_library_configuration" extension in one of your plugins and add a "filteredProperties" element as shown above.

Would this be enough for you, or would you need some other way that didn't involve developing your own custom plugin with the "com.zeligsoft.domain.idl3plus.model_library_configuration" extension?

**Comment by eposse** [comment]
I've rebased and rebuild PR #406. It's been reviews by @ysroh and it's ready for you to test.

**Comment by eposse** [comment]
The link to the RPM is [here](https://github.com/ZeligsoftDev/CX4CBDDS/suites/6933193268/artifacts/269912282).

**Comment by eposse** [comment]
I rebased #406 on top of the latest merged changes. You can get the RPM [here](https://github.com/ZeligsoftDev/CX4CBDDS/suites/6965812113/artifacts/272054299).

**Comment by j26151** [comment]
I have verified this on our end. You can merge it into the baseline.
