### ISSUE TITLE
Combine 2 Connection Icons into 1

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#74]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
Currently there are 2 connection items: connection and CSL. Connection allows for connections for both DDS based connectors as well as client server. CSL allows for DDS based connections as well as CSL **if** the user checks the CSL box.  These two connections should be combined into one and the checkbox is all that is required to get CSL ports.

**Comment by ysroh** [comment]
I am looking into how we generate CSL connection. It looks like we only generate CSL connection if the source port's "hasCSL" field is checked given the ConnectorStatusListenerConnection which means that we can determine if we need to generate CSL from the port regardless of the connection type. In this case, we can just remove the CSLConnection entry from the palette and generate CLS connection from a regular Connection if the source port has CSL checked.

I am wondering if we really need the checkbox for "CSL" on a Connection if we remove CSL connection or not. Please advise.

**Comment by j26151** [comment]
That was what we were thinking. We definitely still want the ability to enable CSL for DDS4CCM based connector ports, but we just want a single connection type. So removing the CSL Connection entry would be great along with keeping the checkbox.

**Comment by ysroh** [comment]
So keep the existing "hasCSL" checkbox on the port and no new checkbox is required if I understand correctly.

**Comment by j26151** [comment]
Yes, I believe that is what we want.

**Comment by ysroh** [comment]
Do you want to migrate CSL connection from the existing model? The CSL connection is still supported but if you want to migrate to make the model consistent then let me know.

**Comment by MHayman5** [comment]
I was following this until this latest question, and wanted to make sure there wasn't a misunderstanding.

When you say "migrate CSL connection" do you mean the UML connector line option/type that interconnects ports (blue line on RSA composite structure diagrams), or the CSL hidden/child basic port associated with its parent pub-sub port on a component, which is added/generated by the "hasCSL" checkbox?

Assuming you're talking about the connection/line type vs. the port, then it wouldn't hurt to migrate the CSL UML connector option to just a single standard UML connector line option for everything (black line on RSA composite structure diagrams).  We still want the CSL connector port itself, just not the option to either "wire it up" or not depending upon the UML connector line/color chosen from the palette.  If the hidden/child basic port is there per the "hasCSL" checkbox, then it would always be connected per any UML connector lines going to its parent pub-sub port.  If "hasCSL" is not checked, then it wouldn't be connected (because it wouldn't exist).

**Comment by ysroh** [comment]
Yes Mark. I meant just the cosmetic connection  not the underlying generated connection in XML file. Thanks for the clarification.

**Comment by ysroh** [comment]
@j26151 Can you please verify this fix and let me know? Thanks.

**Comment by j26151** [comment]
It works great, feel free to close this issue.

**Comment by ysroh** [comment]
Verified.
