### ISSUE TITLE
Open deployment plan editor when double clicking a deployment plan

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#94]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
When double clicking on a deployment plan in Papyrus, nothing happens. This should open the deployment plan editor as it did in RSA.

**Comment by ysroh** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=561874

**Comment by J17359** [comment]
@ysroh - Any word on this from your friends at Papyrus/Eclipse? I know our users will 100% ask why this doesn't work (not blaming you) so figured I'd check in on the status.

**Comment by ysroh** [comment]
@J17359 I don't think anyone will work on this in the near future. I think we have two choices. We can provide a fix to the Papyrus team to commit the fix for us or we can fork the Papyrus branch and maintain this branch as we did for the EMF compare branch. 
The fix isn't simple since we need to provide a framework for the generic action handler for model explorer tree elements.
We will give a little more thought to this and let you know.

**Comment by J17359** [comment]
@ysroh - That's fine! I was just checking in on this issue. I agree that maintaining your own branch wouldn't be the best solution. Would there be any harm in throwing a PR out to the Papyrus team to see if they'd commit it for you? If they don't, we're no worse off than today and if they do, we benefit (assuming the move to that version of Papyrus is possible).

But yes, please let us know what you all decide.

**Comment by ysroh** [comment]
As I was looking into Model Explorer code I think I found a work-around for this issue. I am working on it so I will let you know if I have a fix. Thanks

**Comment by ysroh** [comment]
I implemented a work-around so this should work now.

**Comment by J17359** [comment]
I verified this issue now works as expected. Thanks @ysroh, this is huge!
